name: thera
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flex_color_scheme: ^8.0.1
  flutter_riverpod: ^2.6.1
  uuid: ^4.5.1
  equatable: ^2.0.7
  awesome_extensions: ^2.0.19
  loader_overlay: ^4.0.3
  envied: ^1.0.0
  dio: ^5.7.0
  dart_mappable: ^4.3.0
  retrofit: ^4.4.1
  shared_preferences: ^2.3.3
  go_router: ^14.6.1
  supabase_flutter: ^2.8.1
  riverpod_annotation: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  retrofit_generator: ^9.1.5
  build_runner: ^2.4.13
  custom_lint: ^0.7.0
  riverpod_generator: ^2.6.3


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
